# Generated by Django 5.2.17 on 2026-09-23 21:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la Categoría')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('icon', models.CharField(default='fa-briefcase', help_text='Clase de FontAwesome (ej. fa-code, fa-paint-brush)', max_length=50)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título del Servicio')),
                ('description', models.TextField(verbose_name='Descripción Detallada')),
                ('deliverables', models.TextField(help_text='Listado de lo que recibirá el cliente', verbose_name='Entregables Incluidos')),
                ('estimated_duration', models.CharField(help_text='Ej: 2 horas, 3 días hábiles', max_length=100, verbose_name='Duración Estimada')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1.0)], verbose_name='Tarifa ($ USD / CLP)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Servicio Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
