# Generated by Django 5.2.17 on 2026-09-23 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Total Transado')),
                ('skilly_fee_percentage', models.DecimalField(decimal_places=2, default=15.0, max_digits=5, verbose_name='Comisión Skilly (%)')),
                ('skilly_fee_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Comisión Skilly ($)')),
                ('net_professional_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Neto Profesional ($)')),
                ('payment_gateway', models.CharField(default='SkillyPay Escrow Gateway', max_length=50, verbose_name='Pasarela de Pago')),
                ('escrow_status', models.CharField(choices=[('RETENIDO', 'Retenido en Custodia'), ('LIBERADO', 'Liberado a Profesional'), ('REEMBOLSADO', 'Reembolsado a Organización'), ('CONGELADO_POR_DISPUTA', 'Congelado por Disputa')], default='RETENIDO', max_length=30, verbose_name='Estado de Custodia')),
                ('transaction_id', models.CharField(max_length=100, unique=True, verbose_name='ID de Transacción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transaction', to='bookings.booking')),
            ],
        ),
    ]
