# Generated by Django 5.2.17 on 2026-09-23 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow_payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='authorization_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Código Autorización Transbank'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='buy_order',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Orden de Compra Webpay'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='payment_type_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Tipo Pago Transbank (VN, VC, etc.)'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='session_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID de Sesión Webpay'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='shares_number',
            field=models.IntegerField(default=0, verbose_name='Número de Cuotas'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Token Webpay (token_ws)'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='transbank_response_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Código Respuesta Transbank'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='escrow_status',
            field=models.CharField(choices=[('INICIADA', 'Iniciada en Webpay'), ('RETENIDO', 'Retenido en Custodia Escrow'), ('RECHAZADA', 'Rechazada / Cancelada'), ('LIBERADO', 'Liberado a Profesional'), ('REEMBOLSADO', 'Reembolsado a Organización'), ('CONGELADO_POR_DISPUTA', 'Congelado por Disputa')], default='INICIADA', max_length=30, verbose_name='Estado de Custodia'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='payment_gateway',
            field=models.CharField(default='Webpay Plus Transbank (Sandbox)', max_length=50, verbose_name='Pasarela de Pago'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='transaction_id',
            field=models.CharField(max_length=100, unique=True, verbose_name='ID de Transacción Interna'),
        ),
    ]
