# Generated by Django 5.2.17 on 2026-09-23 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('start_time', models.TimeField(verbose_name='Hora Inicio')),
                ('end_time', models.TimeField(verbose_name='Hora Fin')),
                ('status', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('PRE_RESERVADO', 'Pre-reservado (Bloqueo 20m)'), ('OCUPADO', 'Ocupado')], default='DISPONIBLE', max_length=20)),
                ('reserved_until', models.DateTimeField(blank=True, help_text='Expiración del bloqueo temporal de 20 minutos', null=True)),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
