# Generated by Django 5.2.17 on 2026-09-23 21:42

import disputes.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='Explique la controversia con claridad (Mínimo 50 caracteres).', validators=[disputes.models.validate_min_length_50], verbose_name='Motivo Detallado de la Disputa')),
                ('evidence', models.FileField(blank=True, null=True, upload_to='dispute_evidences/', verbose_name='Evidencia Adjunta (Capturas/Documentos PDF)')),
                ('status', models.CharField(choices=[('ABIERTA', 'Abierta / En Mediación'), ('RESUELTA_PROFESIONAL', 'Resuelta a Favor del Profesional'), ('RESUELTA_ORGANIZACION', 'Resuelta a Favor de la Organización'), ('RESUELTA_MIXTA', 'Resuelta con Acuerdo Mixto')], default='ABIERTA', max_length=30)),
                ('resolution_notes', models.TextField(blank=True, null=True, verbose_name='Notas de Resolución del Administrador')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispute', to='bookings.booking')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
