# Generated by Django 5.2.17 on 2026-09-23 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField(verbose_name='Fecha Agendada')),
                ('start_time', models.TimeField(verbose_name='Hora Inicio')),
                ('end_time', models.TimeField(verbose_name='Hora Fin')),
                ('project_requirements', models.TextField(verbose_name='Requerimientos / Detalles del Proyecto')),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente de Aprobación'), ('PRE_RESERVADA', 'Pre-reservada (Checkout Pendiente)'), ('ACEPTADA', 'Aceptada por Profesional'), ('RECHAZADA', 'Rechazada'), ('PAGADO_EN_CUSTODIA', 'Pagado en Custodia (Escrow)'), ('EN_EJECUCION', 'En Ejecución'), ('ENTREGADO', 'Entregado por Profesional'), ('FINALIZADO', 'Finalizado'), ('EN_DISPUTA', 'En Disputa'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=30)),
                ('cancellation_penalty_applies', models.BooleanField(default=False, help_text='True si se canceló con menos de 24h de anticipación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='booking_chats/', verbose_name='Archivo Adjunto')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
