# Generated by Django 5.2.17 on 2026-09-23 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Título del Beneficio')),
                ('provider', models.CharField(max_length=100, verbose_name='Proveedor / Alianza')),
                ('category', models.CharField(help_text='Ej: Seguros & Salud, Formación, Herramientas Work', max_length=100, verbose_name='Categoría')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='benefit_logos/', verbose_name='Logo / Imagen')),
                ('activation_url', models.URLField(blank=True, default='#', verbose_name='Enlace de Activación')),
                ('badge_text', models.CharField(default='Descuento Exclusivo', max_length=50, verbose_name='Etiqueta Promocional')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
