# Generated by Django 5.2.17 on 2026-09-23 21:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Insignia')),
                ('icon', models.CharField(default='fa-award', help_text='Icono FontAwesome', max_length=50)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(blank=True, help_text='Retroalimentación confidencial de calidad (Máximo 500 caracteres)', max_length=500, validators=[django.core.validators.MaxLengthValidator(500)], verbose_name='Comentarios de Evaluación (Privados - Solo Admin)')),
                ('rating', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Calificación (1-5)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('badges', models.ManyToManyField(related_name='reviews', to='reviews.badge', verbose_name='Insignias Seleccionadas (Min 1, Max 3)')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='bookings.booking')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
